name: Deploy Azure VM using Bicep

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-cli@v1

      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      run: |
        az deployment group create \
          --resource-group ${{ secrets.BH-Team }} \
          --template-file main.bicep \
          az deployment group create --template-file path/to/your/main.bicep --parameters path/to/your/parameters.json
